version: '3'

services:
  planka:
    build:
      context: https://github.com/robertocjunior/planka.git
    restart: on-failure
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 80:1337
    environment:
      # Base URL do Planka
      - BASE_URL=http://192.168.3.8:80
      # URL do banco de dados PostgreSQL
      - DATABASE_URL=postgresql://postgres@postgres/planka
      # Chave secreta para o Planka
      - SECRET_KEY=notsecretkey
      # Variáveis de ambiente existentes
      - DEFAULT_ADMIN_EMAIL=demo@demo.demo
      - DEFAULT_ADMIN_PASSWORD=12345678
      - DEFAULT_ADMIN_NAME=Suporte
      - DEFAULT_ADMIN_USERNAME=Sup
      - SMTP_HOST=smtp.testes.com.br
      - SMTP_PORT=58
      - SMTP_SECURE=false
      - SMTP_USER=teste@nicocereais.com.br
      - SMTP_PASSWORD=Nico@123
      - SMTP_FROM="Planka Notification" <planka@nicocereais.com.br>
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
