FROM node:18-alpine as server-dependencies

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    libc6-compat

WORKDIR /app/client
COPY package.json package-lock.json /app/client/
RUN npm install -g npm@10 \
  && npm install -g pnpm \
  && pnpm import \
  && pnpm install


WORKDIR /app/
COPY ../../package.json ../../package-lock.json /app/
RUN pnpm import \
  && pnpm install
