FROM node:18-alpine as server-dependencies

RUN apk -U upgrade \
  && apk add build-base python3 \
  --no-cache

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install -g npm@10 \
  && npm install -g pnpm \
  && pnpm import \
  && pnpm install
